version: "2"

services:
  web:
    image: nginx
    volumes:
      - /home/admin/docker_space/nginx/html:/usr/share/nginx/html
      - /home/admin/docker_space/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    container_name: nginxbox
